- hosts: access_1_sw
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_python_interpreter: /home/student/ansible_venv/bin/python3
  gather_facts: no
  tasks:
    - name: Create Banner
      aoscx_banner:
        banner_type: banner
        banner: "hello!"